### ISSUE TITLE
Support a Workflow for Fixing Config Errors from this Role

### ISSUE THREAD

**Issue by timblaktu** [nginxinc/ansible-role-nginx-config#39] opened 2020-11-09 23:49 UTC
It is not only possible, but very likely, that at some point when developing a playbook with this role, the role variables used will generate invalid main and/or http config files. The problem is that once the config files on the controlled host are bad, you cannot run the config role without encountering errors in the "Register NGINX Config" task, or without manual intervention to edit the files on the controlled host to make them good. It would be useful for there to be variables that allowed users to "force" the repushing of newly-generated config files (from changed role variables), i.e. skip the check config step. I think it would be even better if the config is not checked until after it is regenerated on the controlled host.

I'm using the nginxinc (open source, core) collection v0.1.3.

**Comment by alessfg** [comment] 2020-11-10 11:57
Hm that is some interesting behaviour. By all means, in my testing, if rerun the playbook with an incorrect variable and then rerun it with a correct variable, the validation task will succeed on the second run. The "Register NGINX Config" task is run after a new template is deployed so it should not be failing if the config has been fixed. I'll try to do some further testing with the collection and see if I can replicate the issue.

**Comment by alessfg** [comment] 2020-11-12 17:29
So, after some more digging, I think I might now what the issue is. The check config handler only runs at the end of the playbook after the config is changed, so the issue is not with the `nginx_config` role. 

However, you might be encountering an issue that'll happen if you run both the `nginx` and `nginx_config` roles within the same playbook if you set `nginx_debug_output: true` in the `nginx` role variables. The `nginx` role will try to verify the config and fail, since the `nginx` role would be running before the `nginx_config` role runs and fixes the config. If you set `nginx_debug_output: false`, you should be able to avoid running into the issue you are describing.

**Comment by alessfg** [comment] 2021-02-17 13:25
There's been no updates in a while so I'm going to go ahead and close this. I'm pretty sure the issue is related to what I described above. Do note that I would recommend only running the `nginx` role only once in your workflows, and then run the `nginx_config` role as many times as necessary.

**Closed by alessfg** 2021-02-17 13:25 UTC
Labels: needs validation
